@host = localhost
@port = 8080

### Retrieve users list
GET http://{{host}}:{{port}}/api/users
Accept: application/json

### Create a new user
POST http://{{host}}:{{port}}/api/users
Content-Type: application/json

{

  "loginId": "test123",
  "userName": "홍길동",
  "email": "hong@example.com",
  "picture": "profile.jpg",
  "phoneNumber": "02-1234-5678",
  "mobilePhoneNumber": "010-1234-5678"
}

> {%
    if (response.status === 200) {
        client.global.set("id", response.body.id)
    }
%}

### Retrieve a single user
GET http://{{host}}:{{port}}/api/users/{{id}}
Accept: application/json

### Update a single user
PUT http://{{host}}:{{port}}/api/users/{{id}}
Content-Type: application/json
Accept: application/json

{
  "loginId": "updatedId123",
  "userName": "임꺽정",
  "email": "updated_email@example.com",
  "picture": "updated_profile.jpg",
  "phoneNumber": "02-9876-5432",
  "mobilePhoneNumber": "010-9876-5432"
}

### Delete a single user
DELETE http://{{host}}:{{port}}/api/users/{{id}}
Accept: application/json
